### ISSUE TITLE
When I visit patents.google.com, the page loads fine initially, but once loaded, it turns white and becomes unviewable due to a Chrome extension that also blocks access to other sites.

### ISSUE THREAD

**Issue by snipeTR** [idriss-crypto/browser-extensions#37]
When I enter patents.google.com, there are no issues during the page loading process. However, once the page finishes loading, the webpage turns white and cannot be displayed. I've encountered similar issues with a couple of other websites before, but they weren't significant, and I could work around them by using incognito mode. Today, after thorough research, I found the above-mentioned errors in Chrome's devtools. I proceeded by disabling all installed extensions and enabling them one by one to troubleshoot. I discovered that your Chrome extension was preventing the page from loading. When I activate the extension shown in the photo below, I am unable to access certain websites.

chrome 126.0.6478.127 official compile
IDriss 1.1.35
antivirus kaspersky

please check it.

**Comment by lennardevertz** [comment]
Thanks, we can reproduce this. 
We will fix it in our next release!
